# ADC configuration
CONFIG_ADC=y
CONFIG_INPUT=y
CONFIG_INPUT_ADC_KEYS=y

# DMA configuration
CONFIG_DMA=y
CONFIG_DMA_ESP32_MAX_DESCRIPTOR_NUM=40

# Debug configuration
CONFIG_DEBUG=y
CONFIG_PRINTK=y
# CONFIG_SHELL=y
# CONFIG_KERNEL_SHELL=y
# CONFIG_SHELL_STACK_SIZE=3072

# Display configuration
CONFIG_DISPLAY=y
CONFIG_ST7789V=y
CONFIG_MIPI_DBI=y
CONFIG_SPI=y

# DNS configuration
CONFIG_DNS_RESOLVER=y
CONFIG_DNS_SERVER_IP_ADDRESSES=y
CONFIG_DNS_SERVER1="8.8.8.8"
CONFIG_DNS_SERVER2="1.1.1.1"
CONFIG_DNS_NUM_CONCUR_QUERIES=3

# Events configuration
CONFIG_EVENTS=y

# GPIO configuration
CONFIG_GPIO=y

# I2C configuration
CONFIG_I2C=y

# Heap configuration
CONFIG_HEAP_MEM_POOL_SIZE=56384

# Log configuration
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3

# LVGL configuration
CONFIG_LVGL=y
CONFIG_LV_USE_LABEL=y
CONFIG_LV_USE_ARC=y
CONFIG_LV_FONT_MONTSERRAT_16=y
CONFIG_LV_Z_MEM_POOL_SIZE=16384
CONFIG_LV_Z_VDB_SIZE=10

# Network configuration
CONFIG_NETWORKING=y
CONFIG_NET_CONFIG_AUTO_INIT=n
CONFIG_NET_CONNECTION_MANAGER=y
CONFIG_NET_DHCPV4=y
CONFIG_NET_IF_MAX_IPV4_COUNT=2
CONFIG_NET_IF_MAX_IPV6_COUNT=2
CONFIG_NET_IPV4=y
CONFIG_NET_L2_WIFI_MGMT=y
CONFIG_NET_MGMT=y
CONFIG_NET_MGMT_EVENT=y
CONFIG_NET_MGMT_EVENT_INFO=y
CONFIG_NET_MGMT_EVENT_QUEUE_SIZE=4
CONFIG_NET_MGMT_EVENT_STACK_SIZE=4096
CONFIG_NET_PKT_RX_COUNT=8
CONFIG_NET_PKT_TX_COUNT=8
CONFIG_NET_SOCKETS=y
CONFIG_NET_SOCKETS_SERVICE_STACK_SIZE=2048
CONFIG_NET_UDP=y
CONFIG_NET_TCP=y
CONFIG_NET_TCP_WORKQ_STACK_SIZE=1024     

# SPIRAM configuration
CONFIG_ESP_SPIRAM=y
CONFIG_SHARED_MULTI_HEAP=y
CONFIG_SPIRAM_MODE_OCT=y
CONFIG_SPIRAM_SPEED_80M=y
CONFIG_ESP32S3_DATA_CACHE_64KB=y
CONFIG_ESP_SPIRAM_MEMTEST=y
CONFIG_ESP32_WIFI_NET_ALLOC_SPIRAM=y

# SNTP configuration
CONFIG_SNTP=y
CONFIG_POSIX_API=y

# UART configuration
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_SERIAL=y

# Video configuration
CONFIG_VIDEO=y
CONFIG_VIDEO_OV2640=y
CONFIG_VIDEO_BUFFER_POOL_ALIGN=32
CONFIG_VIDEO_BUFFER_POOL_NUM_MAX=1
CONFIG_VIDEO_BUFFER_POOL_HEAP_SIZE=159744

# WiFi configuration
CONFIG_WIFI=y
CONFIG_WIFI_NM=y
CONFIG_WIFI_USAGE_MODE_STA=y